/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.App // le decimos a que paquete pertenece y donde tiene que buscar
import org.example.app.Fecha

fun main() {
    println(App().greeting)
    println(Fecha(29, 5, 2026).toString()) //se pone entre parentesis porque se esta creando un objeto de la clase fecha y se le asignan los valores a las variables privadas, luego se llama al metodo toString() para mostrar la fecha en formato string
}
