/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.App // le decimos a que paquete pertenece y donde tiene que buscar

fun main() {
    println (App().get())
    println (App().mostrar())
}